name: "「特美100」美容化妆减肥健身保养抗衰老百科知识"
url:  "https://www.temei100.com"
baseurl:  
img:  /img
logo: logo-112x112.png
imgcdn: 
Copyright: Copyright @2011-2019 All rights reserved.
ICP-number:

encoding: UTF-8
future: true

highlighter: rouge
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

lsi:  false
excerpt_separator: "----"

permalink: pretty
pagination:
  enabled: true
  per_page: 20
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 4
    after: 4
